# Site settings
titles: 
    - title: "<span style='font-family:Menlo, Courier, monospace'>=nil;</span> Foundation"
      url: "https://nil.foundation"
email: "hello@nil.foundation"
url: "https://nil.foundation"
description: ""
subtitle: "Trustless Data Accessibility for&nbsp"
areas: 
    - "Protocols"
    - "Applications"
    - "Bridges"
meta_author: Mikhail Komarov

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: nemo 

# Color settings (hex-codes without the leading hash-tag)
color:
  text-color: F5F2F1
  background-color: 222222
  navbar-color: 222222
  footer-above-color: 222222
  footer-below-color: 222222
  secondary: 907F8F
  secondary-dark: 776475
  secondary-darker: d3d3d3

  background-color-rgb: "37,37,37"

  primary: 725C70
  info: 232125
  success: 57965a
  warning: d58622
  danger: f44336

# Footer settings
footer:
  copyright: =nil; Foundation
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nil_foundation
  - title: linkedin
    url: https://www.linkedin.com/company/nil-foundation
  - title: telegram
    url: https://t.me/nilfoundation
    #  - title: facebook
    #    url:
    #  - title: stack-overflow
    #    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/nilfoundation
  - title: discord
    url: https://discord.gg/XM8jBPx6xp

# Postal address (add as many lines as necessary)
address:
  - title: nil
    location: P.O. box 2775, Artemis House, 67 Fort Street, Grand Cayman, KY1-1111, Cayman Islands
  - title: nil (Cyprus) Ltd. 
    location: Vasileiou Makedonos, 59, 3040, Limassol, Cyprus

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics_id: G-CB8D65YWRZ
