- name: clone application
  ansible.builtin.git:
    repo: https://{{ site_git_token }}@{{ site_repo }}
    version: {{ site_branch }} 
    dest: {{ site_app_dir }}


- name: install dependencies
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ site_app_dir }}/site && npm ci


- name: build repo
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ site_app_dir }}/site && npm run build
  
- name: Install systemd conf
  template: >
    src=systemd.conf.j2
    dest=/etc/systemd/system/{{ site_app_domain }}.service
    owner=root
    group=root
    mode=0755

- name: Ensure services are started and enabled on boot
  become: yes
  become_user: root
  ansible.builtin.systemd:
    name: {{ site_app_domain }}
    state: restarted
    daemon_reload: true

- name: config site
  become: yes
  become_user: root
  notify: restart nginx
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ site_app_domain }}.conf
