
- name: clone application
  ansible.builtin.git:
    repo: https://github.com/nilFoundation/nil.foundation
    version: new-site-scripts 
    dest: {{ site_app_dir }}

- name: install dependencies
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ site_app_dir }}/admin && npm ci

- name: Install systemd conf
  become: yes
  become_user: root
  template: >
    src=systemd.conf.j2
    dest=/etc/systemd/system/{{ site_admin_domain }}.service
    owner=root
    group=root
    mode=0755

- name: Ensure services are started and enabled on boot
  become: yes
  become_user: root
  ansible.builtin.systemd:
    name: {{ site_admin_domain }}
    state: restarted
    daemon_reload: true

- name: config site
  become: yes
  become_user: root
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ site_admin_domain }}.conf